<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => '9f6202de15c390876725d45275ee0ecb5a5e913a',
  'DATABASE_URL' => 'mysql://audio_log_db_usr:eX27kPM6XisXwusk@127.0.0.1:3306/audio_log_db?serverVersion=10.5.27-MariaDB&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'null://null',
);
